Repository dusk-network/dusk-pki, pull requests merged in 2020-09, with the labels that each got.

#8 Fix iteration over bytes in UperHex fmt impl
  src/spend/public.rs
  src/spend/secret.rs
  src/spend/stealth.rs
  src/view.rs
Labels: type:bug

#7 Add basic CI
  .github/workflows/dusk_ci.yml
  src/errors.rs
  src/spend/public.rs
  src/spend/secret.rs
  src/spend/stealth.rs
  src/view.rs
Labels: area:testing

#13 Revert to a more simpler iteration during formatting
  src/spend/public.rs
  src/spend/secret.rs
  src/spend/stealth.rs
  src/view.rs
Labels: type:tech-debt

#15 Change Rustfmt Action to use nightly toolchain
  .github/workflows/dusk_ci.yml
Labels: area:conf&build
