Repository dusk-network/dusk-pki, pull requests merged in 2020-11, with the labels that each got.

#18 Modify CI to match with canonical usage
  .github/workflows/dusk_ci.yml
Labels: area:testing

#17 Add gate-featured Canon usage/derivation.
  .github/workflows/dusk_ci.yml
  Cargo.toml
  rust-toolchain
  src/spend/public.rs
  src/spend/secret.rs
  src/spend/stealth.rs
Labels: area:IPC, type:refactor

#19 Version update
  Cargo.toml
  src/lib.rs
  tests/tests.rs
Labels: type:refactor

#22 Increase tag number
  Cargo.toml
Labels: type:refactor
